import './js/mobile-menu'
import './js/modal'
import './js/book-table/custom-date'
import './js/book-table/custom-select'
import './js/book-table/mask-phone'
import './js/price-modal/price-custom'
import './js/swiper'